name: Auto Release Addon

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP of addon
        run: |
          ADDON_NAME=$(basename $GITHUB_REPOSITORY)
          zip -r "${ADDON_NAME}-${GITHUB_REF_NAME}.zip" "${ADDON_NAME}/"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ github.repository }}-${{ github.ref_name }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
